# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PyOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Non-editable, to be generated by system itself.', unique=True, verbose_name='OTP Unique uuid')),
                ('secret', models.CharField(help_text='Secret used to generate OTP', max_length=50, verbose_name='Source (Requester)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
            ],
            options={
                'verbose_name_plural': 'PyOtp',
                'verbose_name': 'PyOtp',
            },
        ),
    ]
