# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyotp',
            name='count',
            field=models.CharField(blank=True, help_text='OTP Count, to be used in case of HOTP', max_length=50, null=True, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='pyotp',
            name='secret',
            field=models.CharField(help_text='Secret used to generate OTP', max_length=50, verbose_name='Secret'),
        ),
    ]
