# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170501_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyotp',
            name='count',
            field=models.IntegerField(blank=True, help_text='OTP Count, to be used in case of HOTP', null=True, verbose_name='Count'),
        ),
    ]
