# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170501_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyotp',
            name='account_name',
            field=models.CharField(blank=True, help_text='Account Name for Provisioning URI, to be used when need URI for QR code.', max_length=255, null=True, verbose_name='Account Name'),
        ),
        migrations.AddField(
            model_name='pyotp',
            name='initial_count',
            field=models.IntegerField(blank=True, help_text='Initial Count for Provisioning URI.', null=True, verbose_name='Initial Count'),
        ),
        migrations.AddField(
            model_name='pyotp',
            name='interval',
            field=models.IntegerField(blank=True, help_text='OTP Count, to be used in case of TOTP.', null=True, verbose_name='Interval (in seconds)'),
        ),
        migrations.AddField(
            model_name='pyotp',
            name='issuer_name',
            field=models.CharField(blank=True, help_text='Issuer Name for Provisioning URI.', max_length=255, null=True, verbose_name='Issuer Name'),
        ),
        migrations.AddField(
            model_name='pyotp',
            name='otp',
            field=models.IntegerField(default=1, help_text='Generated OTP.', verbose_name='OTP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pyotp',
            name='count',
            field=models.IntegerField(blank=True, help_text='OTP Count, to be used in case of HOTP.', null=True, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='pyotp',
            name='secret',
            field=models.CharField(help_text='Secret used to generate OTP.', max_length=50, verbose_name='Secret'),
        ),
    ]
