# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170501_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyotp',
            name='otp',
            field=models.CharField(help_text='Generated OTP.', max_length=10, verbose_name='OTP'),
        ),
    ]
