# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170501_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pyotp',
            old_name='account_name',
            new_name='name',
        ),
    ]
