apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
         name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresdata
          mountPath: /usr/local/var/postgres
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgres-data
      - name: secrets
        secret:
          secretName: db-passwords

